<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from civicall/xml/schema/CRM/Civicall/CallLog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:4708f752e01a392ae401c78d84b13435)
 */
use CRM_Civicall_ExtensionUtil as E;

/**
 * Database access object for the CallLog entity.
 */
class CRM_Civicall_DAO_CallLog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_call_log';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CallLog ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Activity
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $activity_id;

  /**
   * Call start date
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $call_start_date;

  /**
   * Call end date
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $call_end_date;

  /**
   * Created by contact, FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_id;

  /**
   * Call response, FK to OptionValue
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $call_response_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_call_log';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Call Logs') : E::ts('Call Log');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_id', 'civicrm_activity', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'created_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CallLog ID'),
          'required' => TRUE,
          'where' => 'civicrm_call_log.id',
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'activity_id' => [
          'name' => 'activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Activity ID'),
          'description' => E::ts('FK to Activity'),
          'required' => TRUE,
          'where' => 'civicrm_call_log.activity_id',
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_Activity',
          'add' => NULL,
        ],
        'call_start_date' => [
          'name' => 'call_start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Call Start Date'),
          'description' => E::ts('Call start date'),
          'required' => TRUE,
          'where' => 'civicrm_call_log.call_start_date',
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'call_end_date' => [
          'name' => 'call_end_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Call End Date'),
          'description' => E::ts('Call end date'),
          'required' => TRUE,
          'where' => 'civicrm_call_log.call_end_date',
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'created_id' => [
          'name' => 'created_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Created By Contact ID'),
          'description' => E::ts('Created by contact, FK to Contact'),
          'where' => 'civicrm_call_log.created_id',
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'label' => E::ts("Created By"),
          ],
          'add' => NULL,
        ],
        'call_response_id' => [
          'name' => 'call_response_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Call response id'),
          'description' => E::ts('Call response, FK to OptionValue'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_call_log.call_response_id',
          'export' => TRUE,
          'table_name' => 'civicrm_call_log',
          'entity' => 'CallLog',
          'bao' => 'CRM_Civicall_DAO_CallLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'response',
            'optionEditPath' => 'civicrm/admin/options/response',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'call_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'call_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
